// prisma/seed-mhb.ts
// Adds university profiles sourced from mhbeducation.com/en/colleges.
// Safe to re-run: uses upsert on slug and never deletes existing data.
import { PrismaClient, UniversityType } from '@prisma/client'

const prisma = new PrismaClient()

const universities = [
  // --- Northern Cyprus ---
  {
    slug: 'bahcesehir-cyprus-university',
    nameEn: 'Bahçeşehir Cyprus University', nameAr: 'جامعة بهشاشهير قبرص', nameTr: 'Bahçeşehir Kıbrıs Üniversitesi',
    city: 'nicosia', cityEn: 'Nicosia', cityAr: 'نيقوسيا', cityTr: 'Lefkoşa',
    type: UniversityType.PRIVATE,
    establishedYear: 2016,
    descriptionEn: "Bahçeşehir Cyprus University (BAU Cyprus) is a leading university in Northern Cyprus, established in 2016. It offers English-medium programs across architecture, engineering, business, health sciences, law, pharmacy and tourism, with student exchange opportunities across BAU's international campuses.",
    descriptionAr: 'جامعة بهشاشهير قبرص هي إحدى الجامعات الرائدة في شمال قبرص، تأسست عام 2016. تقدم برامج باللغة الإنجليزية في الهندسة المعمارية والهندسة وإدارة الأعمال والعلوم الصحية والقانون والصيدلة والسياحة، مع فرص للتبادل الطلابي بين حرم بهشاشهير الدولية.',
    descriptionTr: "Bahçeşehir Kıbrıs Üniversitesi (BAU Cyprus), 2016 yılında kurulan Kuzey Kıbrıs'ın önde gelen üniversitelerinden biridir. Mimarlık, mühendislik, işletme, sağlık bilimleri, hukuk, eczacılık ve turizm alanlarında İngilizce programlar sunmaktadır.",
  },
  {
    slug: 'girne-american-university',
    nameEn: 'Girne American University', nameAr: 'جامعة غيرنة الأمريكية', nameTr: 'Girne Amerikan Üniversitesi',
    city: 'kyrenia', cityEn: 'Kyrenia', cityAr: 'كيرينيا', cityTr: 'Girne',
    type: UniversityType.PRIVATE,
    establishedYear: 1985,
    totalStudents: 20000,
    descriptionEn: 'Girne American University (GAU) was the first private university in Northern Cyprus, founded in 1985. Located in the coastal city of Kyrenia, it now hosts over 20,000 students from 135 countries across faculties including medicine, engineering, architecture, law and business.',
    descriptionAr: 'جامعة غيرنة الأمريكية هي أول جامعة خاصة في شمال قبرص، تأسست عام 1985. تقع في مدينة كيرينيا الساحلية، وتضم اليوم أكثر من 20,000 طالب من 135 دولة عبر كليات الطب والهندسة والعمارة والقانون والأعمال.',
    descriptionTr: "Girne Amerikan Üniversitesi (GAU), 1985 yılında kurulan Kuzey Kıbrıs'ın ilk özel üniversitesidir. Sahil kenti Girne'de bulunan üniversite, tıp, mühendislik, mimarlık, hukuk ve işletme gibi fakültelerde 135 ülkeden 20.000'den fazla öğrenciyi ağırlamaktadır.",
  },
  {
    slug: 'cyprus-international-university',
    nameEn: 'Cyprus International University', nameAr: 'جامعة قبرص الدولية', nameTr: 'Uluslararası Kıbrıs Üniversitesi',
    city: 'nicosia', cityEn: 'Nicosia', cityAr: 'نيقوسيا', cityTr: 'Lefkoşa',
    type: UniversityType.PRIVATE,
    establishedYear: 1997,
    descriptionEn: "Cyprus International University (CIU) was founded in 1997 and has grown into one of Northern Cyprus's leading internationally recognized universities. Its million-square-metre campus in northern Nicosia hosts medicine, dentistry, pharmacy, engineering and law faculties alongside research centers focused on sustainability and renewable energy.",
    descriptionAr: 'تأسست جامعة قبرص الدولية عام 1997 وأصبحت من أبرز الجامعات المعترف بها دولياً في شمال قبرص. يضم حرمها الجامعي الممتد على مليون متر مربع في شمال نيقوسيا كليات الطب وطب الأسنان والصيدلة والهندسة والقانون، إلى جانب مراكز بحثية في الاستدامة والطاقة المتجددة.',
    descriptionTr: "Uluslararası Kıbrıs Üniversitesi (CIU), 1997 yılında kurulmuş olup Kuzey Kıbrıs'ın uluslararası alanda tanınan önde gelen üniversitelerinden biri haline gelmiştir. Kuzey Lefkoşa'daki bir milyon metrekarelik kampüsünde tıp, diş hekimliği, eczacılık, mühendislik ve hukuk fakülteleri bulunmaktadır.",
  },
  {
    slug: 'near-east-university',
    nameEn: 'Near East University', nameAr: 'جامعة الشرق الأدنى', nameTr: 'Yakın Doğu Üniversitesi',
    city: 'nicosia', cityEn: 'Nicosia', cityAr: 'نيقوسيا', cityTr: 'Lefkoşa',
    type: UniversityType.PRIVATE,
    establishedYear: 1988,
    totalStudents: 27000,
    descriptionEn: 'Near East University is the largest university in Northern Cyprus, founded in 1988 in Nicosia. With 20 faculties, 32 research centers and over 27,000 students from 143 countries, it ranks among the top 200 universities globally in the Times Higher Education Impact Rankings.',
    descriptionAr: 'جامعة الشرق الأدنى هي أكبر جامعة في شمال قبرص، تأسست عام 1988 في نيقوسيا. تضم 20 كلية و32 مركزاً بحثياً وأكثر من 27,000 طالب من 143 دولة، وتُصنَّف ضمن أفضل 200 جامعة عالمياً في تصنيف التايمز للتأثير.',
    descriptionTr: "Yakın Doğu Üniversitesi, 1988 yılında Lefkoşa'da kurulan Kuzey Kıbrıs'ın en büyük üniversitesidir. 20 fakülte, 32 araştırma merkezi ve 143 ülkeden 27.000'den fazla öğrenciyle Times Higher Education Impact sıralamasında dünyanın en iyi 200 üniversitesi arasında yer almaktadır.",
  },
  {
    slug: 'cyprus-health-and-social-sciences-university',
    nameEn: 'Cyprus Health and Social Sciences University', nameAr: 'جامعة قبرص للعلوم الصحية والاجتماعية', nameTr: 'Kıbrıs Sağlık ve Toplum Bilimleri Üniversitesi',
    city: 'guzelyurt', cityEn: 'Güzelyurt', cityAr: 'غوزيل يورت', cityTr: 'Güzelyurt',
    type: UniversityType.PRIVATE,
    totalStudents: 4100,
    descriptionEn: 'Cyprus Health and Social Sciences University is a Northern Cyprus institution focused on medicine, dentistry, pharmacy and health sciences, with over 4,100 students and 100+ academic staff. English is the main language of instruction, supported by academic partnerships with London South Bank University and several Turkish universities.',
    descriptionAr: 'جامعة قبرص للعلوم الصحية والاجتماعية هي مؤسسة في شمال قبرص تركز على الطب وطب الأسنان والصيدلة والعلوم الصحية، وتضم أكثر من 4,100 طالب وأكثر من 100 عضو هيئة تدريس. اللغة الإنجليزية هي لغة التدريس الرئيسية، بدعم من شراكات أكاديمية مع جامعة لندن الجنوبية وعدة جامعات تركية.',
    descriptionTr: "Kıbrıs Sağlık ve Toplum Bilimleri Üniversitesi, tıp, diş hekimliği, eczacılık ve sağlık bilimlerine odaklanan, 4.100'den fazla öğrenciye ve 100'den fazla akademik personele sahip Kuzey Kıbrıs'taki bir kurumdur.",
  },
  {
    slug: 'european-university-of-lefke',
    nameEn: 'European University of Lefke', nameAr: 'الجامعة الأوروبية في لفكة', nameTr: 'Lefke Avrupa Üniversitesi',
    city: 'lefke', cityEn: 'Lefke', cityAr: 'لفكة', cityTr: 'Lefke',
    type: UniversityType.PUBLIC,
    establishedYear: 1990,
    descriptionEn: "European University of Lefke (EUL) is a public university in Northern Cyprus, established in 1990. It offers internationally recognized bachelor's, master's and PhD programs in medicine, engineering, business and social sciences, including dual-degree opportunities with the University of Bradford.",
    descriptionAr: 'الجامعة الأوروبية في لفكة هي جامعة حكومية في شمال قبرص، تأسست عام 1990. تقدم برامج بكالوريوس وماجستير ودكتوراه معترف بها دولياً في الطب والهندسة وإدارة الأعمال والعلوم الاجتماعية، بما في ذلك فرص الحصول على شهادة مزدوجة مع جامعة برادفورد.',
    descriptionTr: "Lefke Avrupa Üniversitesi (EUL), 1990 yılında kurulan Kuzey Kıbrıs'ta bulunan bir devlet üniversitesidir. Tıp, mühendislik, işletme ve sosyal bilimler alanlarında uluslararası tanınırlığa sahip lisans, yüksek lisans ve doktora programları sunmaktadır.",
  },
  {
    slug: 'university-of-kyrenia',
    nameEn: 'University of Kyrenia', nameAr: 'جامعة كيرينيا', nameTr: 'Girne Üniversitesi',
    city: 'kyrenia', cityEn: 'Kyrenia', cityAr: 'كيرينيا', cityTr: 'Girne',
    type: UniversityType.PRIVATE,
    establishedYear: 2013,
    descriptionEn: "University of Kyrenia was established in 2013 in Northern Cyprus and is recognized as the region's first specialized maritime university, with roots in maritime education dating back to 1978. It has since expanded into medicine, engineering, aviation, law and health sciences.",
    descriptionAr: 'تأسست جامعة كيرينيا عام 2013 في شمال قبرص، وتُعدّ أول جامعة متخصصة في الدراسات البحرية في المنطقة، بجذور تعود إلى عام 1978. توسعت لاحقاً لتشمل الطب والهندسة والطيران والقانون والعلوم الصحية.',
    descriptionTr: "Girne Üniversitesi, 2013 yılında Kuzey Kıbrıs'ta kurulmuş olup, kökleri 1978'e dayanan bölgenin ilk uzmanlaşmış denizcilik üniversitesi olarak tanınmaktadır. Zamanla tıp, mühendislik, havacılık, hukuk ve sağlık bilimlerini de kapsayacak şekilde genişlemiştir.",
  },
  {
    slug: 'eastern-mediterranean-university',
    nameEn: 'Eastern Mediterranean University', nameAr: 'جامعة شرق البحر المتوسط', nameTr: 'Doğu Akdeniz Üniversitesi',
    city: 'famagusta', cityEn: 'Famagusta', cityAr: 'فاماغوستا', cityTr: 'Gazimağusa',
    type: UniversityType.PRIVATE,
    establishedYear: 1979,
    totalStudents: 20000,
    descriptionEn: 'Eastern Mediterranean University (EMU) is one of the oldest universities in Northern Cyprus, founded in 1979. Its 12 faculties host over 20,000 students from 106 countries and 1,100 faculty members from 35 countries, with a global ranking of 601-800 and strong programs in medicine, engineering and communication.',
    descriptionAr: 'جامعة شرق البحر المتوسط هي من أقدم الجامعات في شمال قبرص، تأسست عام 1979. تضم 12 كلية أكثر من 20,000 طالب من 106 دول و1,100 عضو هيئة تدريس من 35 دولة، وتحتل مرتبة عالمية بين 601-800.',
    descriptionTr: "Doğu Akdeniz Üniversitesi (DAÜ), 1979 yılında kurulan Kuzey Kıbrıs'ın en eski üniversitelerinden biridir. 12 fakültesinde 106 ülkeden 20.000'den fazla öğrenci ve 35 ülkeden 1.100 öğretim üyesi bulunmaktadır.",
  },

  // --- Turkey ---
  {
    slug: 'bahcesehir-university',
    nameEn: 'Bahçeşehir University', nameAr: 'جامعة بهشاشهير', nameTr: 'Bahçeşehir Üniversitesi',
    city: 'istanbul', cityEn: 'Istanbul', cityAr: 'إسطنبول', cityTr: 'İstanbul',
    type: UniversityType.PRIVATE,
    establishedYear: 1998,
    descriptionEn: "Bahçeşehir University is one of Turkey's top private universities, founded in 1998 in Istanbul under the motto 'In the Heart of Istanbul.' It was among the first Turkish universities to offer English-medium programs and today spans 11 faculties across 7 campuses with over 37,000 graduates.",
    descriptionAr: 'جامعة بهشاشهير هي من أبرز الجامعات الخاصة في تركيا، تأسست عام 1998 في إسطنبول. كانت من أوائل الجامعات التركية التي قدّمت برامج باللغة الإنجليزية، وتضم اليوم 11 كلية موزعة على 7 حرم جامعية وأكثر من 37,000 خريج.',
    descriptionTr: "Bahçeşehir Üniversitesi, 1998 yılında İstanbul'da kurulan Türkiye'nin önde gelen özel üniversitelerinden biridir. İngilizce eğitim veren ilk Türk üniversitelerinden biri olup, bugün 7 kampüste 11 fakülte ve 37.000'den fazla mezuna sahiptir.",
  },
  {
    slug: 'ankara-science-university',
    nameEn: 'Ankara Science University', nameAr: 'جامعة أنقرة للعلوم', nameTr: 'Ankara Bilim Üniversitesi',
    city: 'ankara', cityEn: 'Ankara', cityAr: 'أنقرة', cityTr: 'Ankara',
    type: UniversityType.PRIVATE,
    establishedYear: 2020,
    descriptionEn: 'Ankara Science University is a private university established in 2020, known for an innovative educational approach that encourages research and creative problem-solving. English is the primary language of instruction across its faculties of engineering, architecture, fine arts, law and humanities.',
    descriptionAr: 'جامعة أنقرة للعلوم هي جامعة خاصة تأسست عام 2020، وتشتهر بنهجها التعليمي المبتكر الذي يشجع البحث العلمي وحل المشكلات بإبداع. اللغة الإنجليزية هي لغة التدريس الأساسية في كليات الهندسة والعمارة والفنون الجميلة والقانون والعلوم الإنسانية.',
    descriptionTr: 'Ankara Bilim Üniversitesi, 2020 yılında kurulan, araştırmayı ve yaratıcı problem çözmeyi teşvik eden yenilikçi bir eğitim yaklaşımıyla tanınan özel bir üniversitedir.',
  },
  {
    slug: 'atilim-university',
    nameEn: 'Atılım University', nameAr: 'جامعة أتيليم', nameTr: 'Atılım Üniversitesi',
    city: 'ankara', cityEn: 'Ankara', cityAr: 'أنقرة', cityTr: 'Ankara',
    type: UniversityType.PRIVATE,
    establishedYear: 1997,
    totalStudents: 10000,
    descriptionEn: 'Atılım University was established in 1997 in Ankara and comprises 7 faculties, 4 vocational schools and 3 graduate institutes. It holds ENAEE and MÜDEK accreditation in engineering, ranks among the top 500 universities worldwide (THE 2016-17), and serves around 10,000 students.',
    descriptionAr: 'تأسست جامعة أتيليم عام 1997 في أنقرة، وتضم 7 كليات و4 مدارس مهنية و3 معاهد دراسات عليا. حاصلة على اعتماد ENAEE وMÜDEK في الهندسة، وتُصنَّف ضمن أفضل 500 جامعة عالمياً، وتخدم نحو 10,000 طالب.',
    descriptionTr: "Atılım Üniversitesi, 1997 yılında Ankara'da kurulmuş olup 7 fakülte, 4 meslek yüksekokulu ve 3 lisansüstü enstitüsünden oluşmaktadır. Mühendislikte ENAEE ve MÜDEK akreditasyonuna sahiptir ve yaklaşık 10.000 öğrenciye hizmet vermektedir.",
  },
  {
    slug: 'ankara-medipol-university',
    nameEn: 'Ankara Medipol University', nameAr: 'جامعة أنقرة ميديبول', nameTr: 'Ankara Medipol Üniversitesi',
    city: 'ankara', cityEn: 'Ankara', cityAr: 'أنقرة', cityTr: 'Ankara',
    type: UniversityType.PRIVATE,
    establishedYear: 2018,
    descriptionEn: 'Ankara Medipol University was founded in 2018 by the Turkish Education, Health, Science and Research Foundation, and is recognized for its medical education, dentistry and engineering programs. It operates 10 affiliated hospitals across Ankara and Istanbul for clinical training.',
    descriptionAr: 'تأسست جامعة أنقرة ميديبول عام 2018 على يد مؤسسة التعليم والصحة والعلوم والبحث التركية، وتشتهر ببرامجها في الطب وطب الأسنان والهندسة. تدير 10 مستشفيات تابعة لها في أنقرة وإسطنبول للتدريب السريري.',
    descriptionTr: 'Ankara Medipol Üniversitesi, 2018 yılında Türkiye Eğitim, Sağlık, Bilim ve Araştırma Vakfı tarafından kurulmuş olup tıp, diş hekimliği ve mühendislik programlarıyla tanınmaktadır.',
  },
  {
    slug: 'istanbul-medipol-university',
    nameEn: 'Istanbul Medipol University', nameAr: 'جامعة إسطنبول ميديبول', nameTr: 'İstanbul Medipol Üniversitesi',
    city: 'istanbul', cityEn: 'Istanbul', cityAr: 'إسطنبول', cityTr: 'İstanbul',
    type: UniversityType.PRIVATE,
    establishedYear: 2009,
    totalStudents: 38297,
    internationalStudents: 5000,
    descriptionEn: "Istanbul Medipol University is one of Turkey's leading private universities, especially for medicine and health sciences, founded in 2009. Across 3 campuses and 9 affiliated hospitals it hosts over 38,000 students, 75 undergraduate programs, and advanced research including 5G engineering work with Samsung.",
    descriptionAr: 'جامعة إسطنبول ميديبول هي من أبرز الجامعات الخاصة في تركيا، خاصة في الطب والعلوم الصحية، تأسست عام 2009. تضم عبر 3 حرم جامعية و9 مستشفيات تابعة أكثر من 38,000 طالب و75 برنامج بكالوريوس.',
    descriptionTr: "İstanbul Medipol Üniversitesi, 2009 yılında kurulan, özellikle tıp ve sağlık bilimleri alanında Türkiye'nin önde gelen özel üniversitelerinden biridir. 3 kampüs ve 9 bağlı hastanede 38.000'den fazla öğrenciye ve 75 lisans programına sahiptir.",
  },
  {
    slug: 'istinye-university',
    nameEn: 'İstinye University', nameAr: 'جامعة إستينيه', nameTr: 'İstinye Üniversitesi',
    city: 'istanbul', cityEn: 'Istanbul', cityAr: 'إسطنبول', cityTr: 'İstanbul',
    type: UniversityType.PRIVATE,
    establishedYear: 2015,
    totalStudents: 10710,
    descriptionEn: "İstinye University was founded in 2015 in Istanbul and focuses on artificial intelligence, medical research and innovation. Across two campuses it offers 63 undergraduate and 29 graduate programs to over 10,700 students, with exchange agreements including Warsaw University of Technology and Sapienza University.",
    descriptionAr: 'تأسست جامعة إستينيه عام 2015 في إسطنبول وتركز على الذكاء الاصطناعي والبحث الطبي والابتكار. تقدم عبر حرمين جامعيين 63 برنامج بكالوريوس و29 برنامج دراسات عليا لأكثر من 10,700 طالب.',
    descriptionTr: "İstinye Üniversitesi, 2015 yılında İstanbul'da kurulmuş olup yapay zeka, tıbbi araştırma ve inovasyona odaklanmaktadır. İki kampüsünde 10.700'den fazla öğrenciye 63 lisans ve 29 lisansüstü program sunmaktadır.",
  },
  {
    slug: 'istanbul-atlas-university',
    nameEn: 'Istanbul Atlas University', nameAr: 'جامعة إسطنبول أطلس', nameTr: 'İstanbul Atlas Üniversitesi',
    city: 'istanbul', cityEn: 'Istanbul', cityAr: 'إسطنبول', cityTr: 'İstanbul',
    type: UniversityType.PRIVATE,
    establishedYear: 2018,
    descriptionEn: 'Istanbul Atlas University was established in 2018 by the Turkish Balkan Foundation for Education, Culture and Health in the Kağıthane district of Istanbul. It comprises 5 faculties and a vocational school, with a library of around 37,000 books and advanced medical laboratories.',
    descriptionAr: 'تأسست جامعة إسطنبول أطلس عام 2018 على يد المؤسسة التركية البلقانية للتعليم والثقافة والصحة في منطقة كاغيتهانه بإسطنبول. تضم 5 كليات ومدرسة مهنية، ومكتبة تحوي نحو 37,000 كتاب ومختبرات طبية متطورة.',
    descriptionTr: "İstanbul Atlas Üniversitesi, 2018 yılında Türk Balkan Eğitim, Kültür ve Sağlık Vakfı tarafından İstanbul'un Kağıthane ilçesinde kurulmuştur. 5 fakülte ve bir meslek yüksekokulundan oluşmaktadır.",
  },
  {
    slug: 'biruni-university',
    nameEn: 'Biruni University', nameAr: 'جامعة البيروني', nameTr: 'Biruni Üniversitesi',
    city: 'istanbul', cityEn: 'Istanbul', cityAr: 'إسطنبول', cityTr: 'İstanbul',
    type: UniversityType.PRIVATE,
    establishedYear: 2014,
    totalStudents: 6550,
    descriptionEn: "Biruni University, named after the scholar Abu Rayhan Al-Biruni, was founded in 2014 in Istanbul's Topkapı district under the slogan 'Future of Science.' It comprises 6 faculties, 3 institutes and a School of Health Services, with over 6,500 undergraduate students and 84 programs.",
    descriptionAr: "سُمّيت جامعة البيروني تيمّناً بالعالم أبو الريحان البيروني، وتأسست عام 2014 في منطقة توبكابي بإسطنبول تحت شعار 'مستقبل العلم'. تضم 6 كليات و3 معاهد ومدرسة للخدمات الصحية، مع أكثر من 6,500 طالب بكالوريوس و84 برنامجاً.",
    descriptionTr: "Alim Ebu Reyhan el-Biruni'nin adını taşıyan Biruni Üniversitesi, 2014 yılında İstanbul'un Topkapı ilçesinde 'Bilimin Geleceği' sloganıyla kurulmuştur. 6 fakülte, 3 enstitü ve bir Sağlık Hizmetleri Meslek Yüksekokulundan oluşmaktadır.",
  },
  {
    slug: 'nisantasi-university',
    nameEn: 'Nişantaşı University', nameAr: 'جامعة نيشان تاشي', nameTr: 'Nişantaşı Üniversitesi',
    city: 'istanbul', cityEn: 'Istanbul', cityAr: 'إسطنبول', cityTr: 'İstanbul',
    type: UniversityType.PRIVATE,
    establishedYear: 2012,
    internationalStudents: 5222,
    descriptionEn: "Nişantaşı University was founded in 2012 in Istanbul and has quickly grown into one of Turkey's fastest-growing universities in technology and artificial intelligence. It maintains over 120 Erasmus agreements across 30 countries and hosts more than 5,200 international students among its 169 academic programs.",
    descriptionAr: 'تأسست جامعة نيشان تاشي عام 2012 في إسطنبول وأصبحت بسرعة من أسرع الجامعات نمواً في تركيا في مجالي التكنولوجيا والذكاء الاصطناعي. لديها أكثر من 120 اتفاقية إيراسموس عبر 30 دولة وتضم أكثر من 5,200 طالب دولي ضمن 169 برنامجاً أكاديمياً.',
    descriptionTr: "Nişantaşı Üniversitesi, 2012 yılında İstanbul'da kurulmuş olup teknoloji ve yapay zeka alanlarında Türkiye'nin en hızlı büyüyen üniversitelerinden biri haline gelmiştir. 30 ülkede 120'den fazla Erasmus anlaşmasına ve 169 akademik programda 5.200'den fazla uluslararası öğrenciye sahiptir.",
  },
  {
    slug: 'yeni-yuzyil-university',
    nameEn: 'Istanbul Yeni Yüzyıl University', nameAr: 'جامعة إسطنبول ييني يوزيل', nameTr: 'İstanbul Yeni Yüzyıl Üniversitesi',
    city: 'istanbul', cityEn: 'Istanbul', cityAr: 'إسطنبول', cityTr: 'İstanbul',
    type: UniversityType.PRIVATE,
    establishedYear: 2009,
    totalStudents: 8580,
    descriptionEn: 'Istanbul Yeni Yüzyıl University was established in 2009 by the Vatan Foundation for Health and Education and is particularly known for its medical programs, offering more than 23 medicine-related degrees. It comprises 10 faculties across two campuses in the Topkapı area of Istanbul, serving over 8,580 students.',
    descriptionAr: 'تأسست جامعة إسطنبول ييني يوزيل عام 2009 على يد مؤسسة وطن للصحة والتعليم، وتشتهر ببرامجها الطبية حيث تقدم أكثر من 23 برنامجاً طبياً. تضم 10 كليات عبر حرمين جامعيين في منطقة توبكابي بإسطنبول، وتخدم أكثر من 8,580 طالباً.',
    descriptionTr: "İstanbul Yeni Yüzyıl Üniversitesi, 2009 yılında Vatan Sağlık ve Eğitim Vakfı tarafından kurulmuş olup, 23'ten fazla tıp programıyla özellikle tıp alanında tanınmaktadır. İstanbul'un Topkapı bölgesindeki iki kampüste 10 fakülte ve 8.580'den fazla öğrenciye sahiptir.",
  },
  {
    slug: 'halic-university',
    nameEn: 'Haliç University', nameAr: 'جامعة هاليتش', nameTr: 'Haliç Üniversitesi',
    city: 'istanbul', cityEn: 'Istanbul', cityAr: 'إسطنبول', cityTr: 'İstanbul',
    type: UniversityType.PRIVATE,
    establishedYear: 1998,
    totalStudents: 12230,
    descriptionEn: "Haliç University was established in 1998 in Istanbul by the Leukemia Foundation for Children and is known for preserving the city's cultural and historical identity within its academic programs. It hosts over 12,000 students and 19,700 graduates across more than 60 research laboratories.",
    descriptionAr: 'تأسست جامعة هاليتش عام 1998 في إسطنبول على يد مؤسسة سرطان الدم للأطفال، وتشتهر بالحفاظ على الهوية الثقافية والتاريخية للمدينة ضمن برامجها الأكاديمية. تضم أكثر من 12,000 طالب و19,700 خريج عبر أكثر من 60 مختبراً بحثياً.',
    descriptionTr: "Haliç Üniversitesi, 1998 yılında İstanbul'da Çocuk Lösemili Vakfı tarafından kurulmuş olup, şehrin kültürel ve tarihi kimliğini akademik programları içinde korumasıyla bilinmektedir. 60'tan fazla araştırma laboratuvarında 12.000'den fazla öğrenciye sahiptir.",
  },
  {
    slug: 'ibn-haldun-university',
    nameEn: 'Ibn Haldun University', nameAr: 'جامعة ابن خلدون', nameTr: 'İbn Haldun Üniversitesi',
    city: 'istanbul', cityEn: 'Istanbul', cityAr: 'إسطنبول', cityTr: 'İstanbul',
    type: UniversityType.PRIVATE,
    establishedYear: 2015,
    descriptionEn: 'Ibn Haldun University, named after the renowned scholar Ibn Khaldun, was founded in 2015 and began teaching in Istanbul\'s Başakşehir district in 2017. It comprises 6 faculties spanning education, law, communication, Islamic sciences, social sciences and administrative sciences, and is known for offering generous scholarships to first-year students.',
    descriptionAr: 'سُمّيت جامعة ابن خلدون تيمّناً بالعالم الشهير ابن خلدون، وتأسست عام 2015 وبدأت التدريس في منطقة باشاك شهير بإسطنبول عام 2017. تضم 6 كليات تشمل التربية والقانون والإعلام والعلوم الإسلامية والعلوم الاجتماعية والعلوم الإدارية، وتشتهر بتقديم منح دراسية سخية لطلاب السنة الأولى.',
    descriptionTr: "Ünlü bilgin İbn Haldun'un adını taşıyan İbn Haldun Üniversitesi, 2015 yılında kurulmuş ve 2017'de İstanbul'un Başakşehir ilçesinde eğitime başlamıştır. Eğitim, hukuk, iletişim, İslami ilimler, sosyal bilimler ve idari bilimler olmak üzere 6 fakülteden oluşmaktadır.",
  },
  {
    slug: 'fenerbahce-university',
    nameEn: 'Fenerbahçe University', nameAr: 'جامعة فنربخشة', nameTr: 'Fenerbahçe Üniversitesi',
    city: 'istanbul', cityEn: 'Istanbul', cityAr: 'إسطنبول', cityTr: 'İstanbul',
    type: UniversityType.PRIVATE,
    establishedYear: 2016,
    descriptionEn: 'Fenerbahçe University was established in 2016 by Fenerbahçe Sports Club and combines a global sporting brand with over 112 years of legacy with modern, research-oriented education. It offers programs in communication, pharmacy, sports sciences, health sciences and engineering, with internship opportunities through the Medicana Group.',
    descriptionAr: 'تأسست جامعة فنربخشة عام 2016 على يد نادي فنربخشة الرياضي، وتجمع بين علامة رياضية عالمية بإرث يمتد لأكثر من 112 عاماً وتعليم حديث موجّه نحو البحث العلمي. تقدم برامج في الإعلام والصيدلة والعلوم الرياضية والعلوم الصحية والهندسة.',
    descriptionTr: "Fenerbahçe Üniversitesi, 2016 yılında Fenerbahçe Spor Kulübü tarafından kurulmuş olup, 112 yılı aşkın mirasa sahip küresel bir spor markasını modern, araştırma odaklı eğitimle birleştirmektedir.",
  },
  {
    slug: 'istanbul-kent-university',
    nameEn: 'İstanbul Kent University', nameAr: 'جامعة إسطنبول كنت', nameTr: 'İstanbul Kent Üniversitesi',
    city: 'istanbul', cityEn: 'Istanbul', cityAr: 'إسطنبول', cityTr: 'İstanbul',
    type: UniversityType.PRIVATE,
    establishedYear: 2016,
    totalStudents: 3000,
    descriptionEn: 'İstanbul Kent University is a private non-profit university founded in 2016 by the Education Without Barriers Foundation. It comprises 4 faculties — humanities and social sciences, arts and design, health sciences and dentistry — serving around 3,000 students with the option to study a second major free of charge.',
    descriptionAr: 'جامعة إسطنبول كنت هي جامعة خاصة غير ربحية تأسست عام 2016 على يد مؤسسة التعليم بلا حدود. تضم 4 كليات هي العلوم الإنسانية والاجتماعية، والفنون والتصميم، والعلوم الصحية، وطب الأسنان، وتخدم نحو 3,000 طالب مع إمكانية دراسة تخصص إضافي مجاناً.',
    descriptionTr: 'İstanbul Kent Üniversitesi, 2016 yılında Engelsiz Eğitim Vakfı tarafından kurulan özel, kar amacı gütmeyen bir üniversitedir. İnsani ve sosyal bilimler, sanat ve tasarım, sağlık bilimleri ve diş hekimliği olmak üzere 4 fakülteden oluşmaktadır.',
  },
  {
    slug: 'istanbul-kultur-university',
    nameEn: 'Istanbul Kültür University', nameAr: 'جامعة إسطنبول كولتور', nameTr: 'İstanbul Kültür Üniversitesi',
    city: 'istanbul', cityEn: 'Istanbul', cityAr: 'إسطنبول', cityTr: 'İstanbul',
    type: UniversityType.PRIVATE,
    establishedYear: 1997,
    descriptionEn: "Istanbul Kültür University was founded in 1997 by the Kültür Educational Foundation, one of Turkey's oldest educational institutions. It comprises 8 faculties and 2 vocational schools, and allows students to pursue a second major alongside their primary field free of charge.",
    descriptionAr: 'تأسست جامعة إسطنبول كولتور عام 1997 على يد مؤسسة كولتور التعليمية، وهي من أقدم المؤسسات التعليمية في تركيا. تضم 8 كليات ومدرستين مهنيتين، وتتيح للطلاب دراسة تخصص ثانٍ إلى جانب تخصصهم الأساسي مجاناً.',
    descriptionTr: 'İstanbul Kültür Üniversitesi, Türkiye\'nin en eski eğitim kurumlarından biri olan Kültür Eğitim Vakfı tarafından 1997 yılında kurulmuştur. 8 fakülte ve 2 meslek yüksekokulundan oluşmaktadır.',
  },
  {
    slug: 'istanbul-okan-university',
    nameEn: 'Istanbul Okan University', nameAr: 'جامعة إسطنبول أوكان', nameTr: 'İstanbul Okan Üniversitesi',
    city: 'istanbul', cityEn: 'Istanbul', cityAr: 'إسطنبول', cityTr: 'İstanbul',
    type: UniversityType.PRIVATE,
    establishedYear: 1999,
    descriptionEn: "Istanbul Okan University was founded in 1999 under the motto 'The University Closest to Real Life' and began teaching in 2003. With 10 faculties and strong industry partnerships for internships, it has produced over 35,000 graduates and includes medicine, pharmacy, engineering and dentistry programs.",
    descriptionAr: "تأسست جامعة إسطنبول أوكان عام 1999 تحت شعار 'الجامعة الأقرب إلى الحياة الواقعية' وبدأت التدريس عام 2003. تضم 10 كليات وشراكات قوية مع الشركات لفرص التدريب، وقد تخرّج منها أكثر من 35,000 طالب في برامج الطب والصيدلة والهندسة وطب الأسنان.",
    descriptionTr: "İstanbul Okan Üniversitesi, 'Gerçek Hayata En Yakın Üniversite' sloganıyla 1999 yılında kurulmuş ve 2003 yılında eğitime başlamıştır. 10 fakültesi ve staj için güçlü sektör ortaklıklarıyla 35.000'den fazla mezun vermiştir.",
  },
  {
    slug: 'fatih-sultan-mehmet-university',
    nameEn: 'Fatih Sultan Mehmet Vakıf University', nameAr: 'جامعة الفاتح سلطان محمد', nameTr: 'Fatih Sultan Mehmet Vakıf Üniversitesi',
    city: 'istanbul', cityEn: 'Istanbul', cityAr: 'إسطنبول', cityTr: 'İstanbul',
    type: UniversityType.PRIVATE,
    establishedYear: 2010,
    totalStudents: 14000,
    descriptionEn: 'Fatih Sultan Mehmet Vakıf University is a non-profit foundation university established in 2010 by several Istanbul waqf foundations, with 6 campuses spanning both sides of the Bosphorus. Instruction is offered in Arabic, English and Turkish across 8 faculties serving 14,000 students.',
    descriptionAr: 'جامعة الفاتح سلطان محمد هي جامعة وقفية غير ربحية تأسست عام 2010 على يد عدة أوقاف في إسطنبول، وتضم 6 حرم جامعية موزعة على جانبي البوسفور. يُقدَّم التدريس باللغات العربية والإنجليزية والتركية عبر 8 كليات تخدم 14,000 طالب.',
    descriptionTr: "Fatih Sultan Mehmet Vakıf Üniversitesi, 2010 yılında birkaç İstanbul vakfı tarafından kurulan, Boğaz'ın her iki yakasında 6 kampüsü bulunan kar amacı gütmeyen bir vakıf üniversitesidir. 8 fakültesinde Arapça, İngilizce ve Türkçe eğitim vermektedir.",
  },
  {
    slug: 'beykent-university',
    nameEn: 'Beykent University', nameAr: 'جامعة بيكنت', nameTr: 'Beykent Üniversitesi',
    city: 'istanbul', cityEn: 'Istanbul', cityAr: 'إسطنبول', cityTr: 'İstanbul',
    type: UniversityType.PRIVATE,
    establishedYear: 1997,
    totalStudents: 30000,
    descriptionEn: "Beykent University was founded in 1997 in Istanbul's Beylikdüzü district by the Beykent Educational Foundation. Spanning 4 campuses on both the European and Asian sides of the city, it comprises 10 faculties and 12 research centers serving around 30,000 students.",
    descriptionAr: 'تأسست جامعة بيكنت عام 1997 في منطقة بيليكدوزو بإسطنبول على يد مؤسسة بيكنت التعليمية. تمتد عبر 4 حرم جامعية على الجانبين الأوروبي والآسيوي من المدينة، وتضم 10 كليات و12 مركزاً بحثياً تخدم نحو 30,000 طالب.',
    descriptionTr: "Beykent Üniversitesi, 1997 yılında İstanbul'un Beylikdüzü ilçesinde Beykent Eğitim Vakfı tarafından kurulmuştur. Şehrin Avrupa ve Anadolu yakalarında 4 kampüse yayılan üniversite, 10 fakülte ve 12 araştırma merkeziyle yaklaşık 30.000 öğrenciye hizmet vermektedir.",
  },
  {
    slug: 'istanbul-topkapi-university',
    nameEn: 'Istanbul Topkapı University', nameAr: 'جامعة إسطنبول توبكابي', nameTr: 'İstanbul Topkapı Üniversitesi',
    city: 'istanbul', cityEn: 'Istanbul', cityAr: 'إسطنبول', cityTr: 'İstanbul',
    type: UniversityType.PRIVATE,
    establishedYear: 2016,
    totalStudents: 8168,
    descriptionEn: "Istanbul Topkapı University was founded in 2016 (originally as İnan Saray University, renamed in 2022) and comprises 5 faculties across 4 campuses. It serves over 8,100 students through 12 bachelor's and 14 master's programs, with a strong focus on art, design and Erasmus exchange opportunities.",
    descriptionAr: 'تأسست جامعة إسطنبول توبكابي عام 2016 (باسم جامعة إينان سراي في البداية، وأُعيدت تسميتها عام 2022) وتضم 5 كليات عبر 4 حرم جامعية. تخدم أكثر من 8,100 طالب عبر 12 برنامج بكالوريوس و14 برنامج ماجستير.',
    descriptionTr: "İstanbul Topkapı Üniversitesi, 2016 yılında (başlangıçta İnan Saray Üniversitesi adıyla, 2022'de yeniden adlandırılarak) kurulmuş olup 4 kampüste 5 fakülteden oluşmaktadır. 12 lisans ve 14 yüksek lisans programıyla 8.100'den fazla öğrenciye hizmet vermektedir.",
  },
  {
    slug: 'istanbul-sabahattin-zaim-university',
    nameEn: 'Istanbul Sabahattin Zaim University', nameAr: 'جامعة إسطنبول صباحات الدين زعيم', nameTr: 'İstanbul Sabahattin Zaim Üniversitesi',
    city: 'istanbul', cityEn: 'Istanbul', cityAr: 'إسطنبول', cityTr: 'İstanbul',
    type: UniversityType.PRIVATE,
    establishedYear: 2010,
    totalStudents: 7483,
    internationalStudents: 2231,
    descriptionEn: 'Istanbul Sabahattin Zaim University is a private non-profit waqf university founded in 2010, located in a historic building dating to 1892. It comprises 8 faculties including engineering, health sciences, Islamic sciences and law, with over 2,200 international students among its 7,483-strong student body.',
    descriptionAr: 'جامعة إسطنبول صباحات الدين زعيم هي جامعة وقفية خاصة غير ربحية تأسست عام 2010، وتقع في مبنى تاريخي يعود إلى عام 1892. تضم 8 كليات منها الهندسة والعلوم الصحية والعلوم الإسلامية والقانون، مع أكثر من 2,200 طالب دولي من أصل 7,483 طالباً.',
    descriptionTr: 'İstanbul Sabahattin Zaim Üniversitesi, 2010 yılında kurulan, 1892 yılına dayanan tarihi bir binada yer alan kar amacı gütmeyen özel bir vakıf üniversitesidir. Mühendislik, sağlık bilimleri, İslami ilimler ve hukuk dahil 8 fakülteden oluşmaktadır.',
  },
  {
    slug: 'esenyurt-university',
    nameEn: 'Istanbul Esenyurt University', nameAr: 'جامعة إسطنبول إسنيورت', nameTr: 'İstanbul Esenyurt Üniversitesi',
    city: 'istanbul', cityEn: 'Istanbul', cityAr: 'إسطنبول', cityTr: 'İstanbul',
    type: UniversityType.PRIVATE,
    establishedYear: 2013,
    totalStudents: 6020,
    internationalStudents: 1030,
    descriptionEn: 'Istanbul Esenyurt University was established in 2013 by the Yeşilköy Foundation for Education, Culture and Health in the Esenyurt district. It comprises 4 main faculties covering business, engineering, architecture, social sciences and health sciences, serving over 6,000 students including 1,030 international students.',
    descriptionAr: 'تأسست جامعة إسطنبول إسنيورت عام 2013 على يد مؤسسة يشيلكوي للتعليم والثقافة والصحة في منطقة إسنيورت. تضم 4 كليات رئيسية تغطي الأعمال والهندسة والعمارة والعلوم الاجتماعية والعلوم الصحية، وتخدم أكثر من 6,000 طالب من بينهم 1,030 طالباً دولياً.',
    descriptionTr: 'İstanbul Esenyurt Üniversitesi, 2013 yılında Yeşilköy Eğitim, Kültür ve Sağlık Vakfı tarafından Esenyurt ilçesinde kurulmuştur. İşletme, mühendislik, mimarlık, sosyal bilimler ve sağlık bilimlerini kapsayan 4 ana fakülteden oluşmaktadır.',
  },
  {
    slug: 'istanbul-gedik-university',
    nameEn: 'Istanbul Gedik University', nameAr: 'جامعة إسطنبول جيديك', nameTr: 'İstanbul Gedik Üniversitesi',
    city: 'istanbul', cityEn: 'Istanbul', cityAr: 'إسطنبول', cityTr: 'İstanbul',
    type: UniversityType.PRIVATE,
    establishedYear: 2010,
    descriptionEn: 'Istanbul Gedik University was founded in 2010 in the Kartal district of Istanbul by engineer Halil Kaya. It runs more than 23 research centers and offers students the opportunity to study a semester or full academic year in Europe through the Erasmus program.',
    descriptionAr: 'تأسست جامعة إسطنبول جيديك عام 2010 في منطقة كارتال بإسطنبول على يد المهندس خليل كايا. تدير أكثر من 23 مركزاً بحثياً وتتيح للطلاب فرصة الدراسة لفصل دراسي أو عام أكاديمي كامل في أوروبا عبر برنامج إيراسموس.',
    descriptionTr: "İstanbul Gedik Üniversitesi, 2010 yılında İstanbul'un Kartal ilçesinde mühendis Halil Kaya tarafından kurulmuştur. 23'ten fazla araştırma merkezi işletmekte ve öğrencilere Erasmus programı aracılığıyla Avrupa'da bir dönem veya tam akademik yıl okuma fırsatı sunmaktadır.",
  },
  {
    slug: 'isik-university',
    nameEn: 'Işık University', nameAr: 'جامعة إشيق', nameTr: 'Işık Üniversitesi',
    city: 'istanbul', cityEn: 'Istanbul', cityAr: 'إسطنبول', cityTr: 'İstanbul',
    type: UniversityType.PRIVATE,
    establishedYear: 1996,
    totalStudents: 6816,
    internationalStudents: 934,
    descriptionEn: 'Işık University was established in 1996 by the Feyziye Schools Foundation, with campuses in Şile and Maslak, Istanbul. It offers 41 undergraduate, 33 master\'s and 6 PhD programs in English and Turkish, and maintains 81 Erasmus partnership agreements.',
    descriptionAr: 'تأسست جامعة إشيق عام 1996 على يد مؤسسة مدارس فيضية، وتضم حرمين في شيله ومصلق بإسطنبول. تقدم 41 برنامج بكالوريوس و33 برنامج ماجستير و6 برامج دكتوراه باللغتين الإنجليزية والتركية، وتحافظ على 81 اتفاقية شراكة إيراسموس.',
    descriptionTr: "Işık Üniversitesi, 1996 yılında Feyziye Mektepleri Vakfı tarafından kurulmuş olup İstanbul'un Şile ve Maslak kampüslerinde yer almaktadır. İngilizce ve Türkçe olarak 41 lisans, 33 yüksek lisans ve 6 doktora programı sunmakta, 81 Erasmus anlaşmasını sürdürmektedir.",
  },
  {
    slug: 'hasan-kalyoncu-university',
    nameEn: 'Hasan Kalyoncu University', nameAr: 'جامعة حسن قالي أونجو', nameTr: 'Hasan Kalyoncu Üniversitesi',
    city: 'gaziantep', cityEn: 'Gaziantep', cityAr: 'غازي عنتاب', cityTr: 'Gaziantep',
    type: UniversityType.PRIVATE,
    establishedYear: 2008,
    totalStudents: 6289,
    descriptionEn: "Hasan Kalyoncu University was established in 2008 in Gaziantep by the Education and Service Foundation, under the motto 'Education with you for a lifetime.' It comprises 8 faculties and 16 research centers, with instruction offered in English and Turkish across selected programs.",
    descriptionAr: "تأسست جامعة حسن قالي أونجو عام 2008 في غازي عنتاب على يد مؤسسة التعليم والخدمة، تحت شعار 'التعليم معك مدى الحياة'. تضم 8 كليات و16 مركزاً بحثياً، ويُقدَّم التدريس باللغتين الإنجليزية والتركية في برامج مختارة.",
    descriptionTr: "Hasan Kalyoncu Üniversitesi, 2008 yılında Gaziantep'te Eğitim ve Hizmet Vakfı tarafından 'Ömür boyu seninle eğitim' sloganıyla kurulmuştur. 8 fakülte ve 16 araştırma merkezinden oluşmaktadır.",
  },
]

async function main() {
  console.log(`Seeding ${universities.length} universities from MHB source (upsert, non-destructive)...`)
  let created = 0
  let updated = 0
  for (const uni of universities) {
    const existing = await prisma.university.findUnique({ where: { slug: uni.slug } })
    await prisma.university.upsert({
      where: { slug: uni.slug },
      update: uni,
      create: { ...uni, isActive: true, isFeatured: false },
    })
    if (existing) updated++
    else created++
  }
  console.log(`Done. Created ${created}, updated ${updated}.`)
}

main()
  .catch((e) => { console.error(e); process.exit(1) })
  .finally(async () => { await prisma.$disconnect() })
