// prisma/seed-turkish-state-universities.ts
// Adds well-known Turkish state (government) university profiles.
// Safe to re-run: uses upsert on slug and never deletes existing data.
import { PrismaClient, UniversityType } from '@prisma/client'

const prisma = new PrismaClient()

const universities = [
  {
    slug: 'marmara-university',
    nameEn: 'Marmara University', nameAr: 'جامعة مرمرة', nameTr: 'Marmara Üniversitesi',
    city: 'istanbul', cityEn: 'Istanbul', cityAr: 'إسطنبول', cityTr: 'İstanbul',
    type: UniversityType.PUBLIC, establishedYear: 1883,
    descriptionEn: "Marmara University is one of Turkey's largest and oldest state universities, tracing its roots to 1883 and based in Istanbul. It comprises over a dozen faculties spanning medicine, law, business, communication and engineering, and is particularly renowned for its business and communication faculties.",
    descriptionAr: 'جامعة مرمرة هي واحدة من أكبر وأقدم الجامعات الحكومية في تركيا، ويعود تاريخها إلى عام 1883 وتقع في إسطنبول. تضم أكثر من اثنتي عشرة كلية تشمل الطب والقانون وإدارة الأعمال والإعلام والهندسة، وتشتهر بشكل خاص بكليتي إدارة الأعمال والإعلام.',
    descriptionTr: "Marmara Üniversitesi, kökleri 1883'e dayanan ve İstanbul'da bulunan Türkiye'nin en büyük ve en köklü devlet üniversitelerinden biridir. Tıp, hukuk, işletme, iletişim ve mühendislik gibi çok sayıda fakülteden oluşmakta olup özellikle işletme ve iletişim fakülteleriyle tanınmaktadır.",
  },
  {
    slug: 'yildiz-technical-university',
    nameEn: 'Yıldız Technical University', nameAr: 'جامعة يلدز التقنية', nameTr: 'Yıldız Teknik Üniversitesi',
    city: 'istanbul', cityEn: 'Istanbul', cityAr: 'إسطنبول', cityTr: 'İstanbul',
    type: UniversityType.PUBLIC, establishedYear: 1911,
    descriptionEn: 'Yıldız Technical University (YTU) is a leading state technical university in Istanbul with roots dating back to 1911, gaining full university status in 1992. It specializes in engineering, architecture and applied sciences, with a historic campus on the Bosphorus.',
    descriptionAr: 'جامعة يلدز التقنية هي جامعة حكومية تقنية رائدة في إسطنبول، يعود تاريخها إلى عام 1911 وحصلت على مكانة جامعة كاملة عام 1992. تتخصص في الهندسة والعمارة والعلوم التطبيقية، وتضم حرماً تاريخياً على مضيق البوسفور.',
    descriptionTr: "Yıldız Teknik Üniversitesi (YTÜ), kökleri 1911'e dayanan ve 1992'de tam üniversite statüsü kazanan İstanbul'daki önde gelen devlet teknik üniversitesidir. Mühendislik, mimarlık ve uygulamalı bilimlerde uzmanlaşmış olup Boğaz kıyısında tarihi bir kampüse sahiptir.",
  },
  {
    slug: 'gazi-university',
    nameEn: 'Gazi University', nameAr: 'جامعة غازي', nameTr: 'Gazi Üniversitesi',
    city: 'ankara', cityEn: 'Ankara', cityAr: 'أنقرة', cityTr: 'Ankara',
    type: UniversityType.PUBLIC, establishedYear: 1926,
    descriptionEn: "Gazi University was founded in 1926 in Ankara as a teacher training institute and has grown into one of Turkey's largest state universities, with strong programs in education, engineering, medicine and technology.",
    descriptionAr: 'تأسست جامعة غازي عام 1926 في أنقرة كمعهد لإعداد المعلمين، وتطورت لتصبح واحدة من أكبر الجامعات الحكومية في تركيا، ببرامج قوية في التربية والهندسة والطب والتكنولوجيا.',
    descriptionTr: 'Gazi Üniversitesi, 1926 yılında Ankara\'da bir öğretmen okulu olarak kurulmuş ve eğitim, mühendislik, tıp ve teknoloji alanlarında güçlü programlarıyla Türkiye\'nin en büyük devlet üniversitelerinden biri haline gelmiştir.',
  },
  {
    slug: 'dokuz-eylul-university',
    nameEn: 'Dokuz Eylül University', nameAr: 'جامعة دوكوز إيلول', nameTr: 'Dokuz Eylül Üniversitesi',
    city: 'izmir', cityEn: 'Izmir', cityAr: 'إزمير', cityTr: 'İzmir',
    type: UniversityType.PUBLIC, establishedYear: 1982,
    descriptionEn: "Dokuz Eylül University was established in 1982 in Izmir and is one of the largest state universities on Turkey's Aegean coast, known for its medical, engineering and business faculties across multiple campuses.",
    descriptionAr: 'تأسست جامعة دوكوز إيلول عام 1982 في إزمير وهي واحدة من أكبر الجامعات الحكومية على الساحل الإيجي لتركيا، وتشتهر بكليات الطب والهندسة وإدارة الأعمال عبر عدة حرم جامعية.',
    descriptionTr: "Dokuz Eylül Üniversitesi, 1982 yılında İzmir'de kurulmuş olup Türkiye'nin Ege kıyısındaki en büyük devlet üniversitelerinden biridir; tıp, mühendislik ve işletme fakülteleriyle tanınmaktadır.",
  },
  {
    slug: 'selcuk-university',
    nameEn: 'Selçuk University', nameAr: 'جامعة سلجوق', nameTr: 'Selçuk Üniversitesi',
    city: 'konya', cityEn: 'Konya', cityAr: 'قونيا', cityTr: 'Konya',
    type: UniversityType.PUBLIC, establishedYear: 1975,
    descriptionEn: "Selçuk University, founded in 1975 in Konya, is one of Turkey's largest state universities with a broad range of faculties spanning medicine, agriculture, engineering and the arts.",
    descriptionAr: 'جامعة سلجوق، التي تأسست عام 1975 في قونيا، هي واحدة من أكبر الجامعات الحكومية في تركيا وتضم مجموعة واسعة من الكليات تشمل الطب والزراعة والهندسة والفنون.',
    descriptionTr: '1975 yılında Konya\'da kurulan Selçuk Üniversitesi, tıp, ziraat, mühendislik ve sanat gibi geniş bir fakülte yelpazesine sahip Türkiye\'nin en büyük devlet üniversitelerinden biridir.',
  },
  {
    slug: 'erciyes-university',
    nameEn: 'Erciyes University', nameAr: 'جامعة إرجييس', nameTr: 'Erciyes Üniversitesi',
    city: 'kayseri', cityEn: 'Kayseri', cityAr: 'قيصري', cityTr: 'Kayseri',
    type: UniversityType.PUBLIC, establishedYear: 1978,
    descriptionEn: 'Erciyes University was founded in 1978 in Kayseri and has grown into a major research university in central Anatolia, with particular strength in medicine and engineering.',
    descriptionAr: 'تأسست جامعة إرجييس عام 1978 في قيصري، وتطورت لتصبح جامعة بحثية رئيسية في وسط الأناضول، مع قوة خاصة في الطب والهندسة.',
    descriptionTr: 'Erciyes Üniversitesi, 1978 yılında Kayseri\'de kurulmuş olup, özellikle tıp ve mühendislik alanlarında güçlü, Orta Anadolu\'nun önde gelen araştırma üniversitelerinden biri haline gelmiştir.',
  },
  {
    slug: 'akdeniz-university',
    nameEn: 'Akdeniz University', nameAr: 'جامعة أكدنيز', nameTr: 'Akdeniz Üniversitesi',
    city: 'antalya', cityEn: 'Antalya', cityAr: 'أنطاليا', cityTr: 'Antalya',
    type: UniversityType.PUBLIC, establishedYear: 1982,
    descriptionEn: 'Akdeniz University was established in 1982 in the Mediterranean city of Antalya, known for its medical school, agriculture and tourism faculties, and a scenic seaside campus.',
    descriptionAr: 'تأسست جامعة أكدنيز عام 1982 في مدينة أنطاليا المتوسطية، وتشتهر بكلية الطب والزراعة والسياحة وحرم جامعي ساحلي خلاب.',
    descriptionTr: 'Akdeniz Üniversitesi, 1982 yılında Akdeniz kıyısındaki Antalya\'da kurulmuş olup tıp fakültesi, ziraat ve turizm fakülteleri ile deniz manzaralı kampüsüyle tanınmaktadır.',
  },
  {
    slug: 'cukurova-university',
    nameEn: 'Çukurova University', nameAr: 'جامعة تشوكوروفا', nameTr: 'Çukurova Üniversitesi',
    city: 'adana', cityEn: 'Adana', cityAr: 'أضنة', cityTr: 'Adana',
    type: UniversityType.PUBLIC, establishedYear: 1973,
    descriptionEn: 'Çukurova University, founded in 1973 in Adana, is a leading state university in southern Turkey with strong agriculture, medicine and engineering programs.',
    descriptionAr: 'جامعة تشوكوروفا، التي تأسست عام 1973 في أضنة، هي جامعة حكومية رائدة في جنوب تركيا ببرامج قوية في الزراعة والطب والهندسة.',
    descriptionTr: '1973 yılında Adana\'da kurulan Çukurova Üniversitesi, güçlü ziraat, tıp ve mühendislik programlarıyla Güney Türkiye\'nin önde gelen devlet üniversitelerinden biridir.',
  },
  {
    slug: 'karadeniz-technical-university',
    nameEn: 'Karadeniz Technical University', nameAr: 'جامعة كارادنيز التقنية', nameTr: 'Karadeniz Teknik Üniversitesi',
    city: 'trabzon', cityEn: 'Trabzon', cityAr: 'طرابزون', cityTr: 'Trabzon',
    type: UniversityType.PUBLIC, establishedYear: 1955,
    descriptionEn: "Karadeniz Technical University (KTU) was founded in 1955 in Trabzon and is the leading technical university on Turkey's Black Sea coast, specializing in engineering, forestry and marine sciences.",
    descriptionAr: 'تأسست جامعة كارادنيز التقنية عام 1955 في طرابزون، وهي الجامعة التقنية الرائدة على ساحل البحر الأسود التركي، وتتخصص في الهندسة والغابات والعلوم البحرية.',
    descriptionTr: "Karadeniz Teknik Üniversitesi (KTÜ), 1955 yılında Trabzon'da kurulmuş olup mühendislik, ormancılık ve deniz bilimlerinde uzmanlaşan Türkiye'nin Karadeniz kıyısındaki önde gelen teknik üniversitesidir.",
  },
  {
    slug: 'ataturk-university',
    nameEn: 'Atatürk University', nameAr: 'جامعة أتاتورك', nameTr: 'Atatürk Üniversitesi',
    city: 'erzurum', cityEn: 'Erzurum', cityAr: 'أرضروم', cityTr: 'Erzurum',
    type: UniversityType.PUBLIC, establishedYear: 1957,
    descriptionEn: 'Atatürk University was established in 1957 in Erzurum as one of the first state universities in eastern Turkey, offering a comprehensive range of programs including medicine, agriculture and engineering.',
    descriptionAr: 'تأسست جامعة أتاتورك عام 1957 في أرضروم كواحدة من أوائل الجامعات الحكومية في شرق تركيا، وتقدم مجموعة شاملة من البرامج تشمل الطب والزراعة والهندسة.',
    descriptionTr: "Atatürk Üniversitesi, 1957 yılında Erzurum'da Doğu Anadolu'nun ilk devlet üniversitelerinden biri olarak kurulmuş olup tıp, ziraat ve mühendislik dahil geniş bir program yelpazesi sunmaktadır.",
  },
  {
    slug: 'anadolu-university',
    nameEn: 'Anadolu University', nameAr: 'جامعة الأناضول', nameTr: 'Anadolu Üniversitesi',
    city: 'eskisehir', cityEn: 'Eskişehir', cityAr: 'إسكيشهير', cityTr: 'Eskişehir',
    type: UniversityType.PUBLIC, establishedYear: 1958,
    descriptionEn: "Anadolu University traces its origins to 1958 in Eskişehir and is renowned for running one of the world's largest distance-education systems alongside strong on-campus programs in business, communication and fine arts.",
    descriptionAr: 'يعود تاريخ جامعة الأناضول إلى عام 1958 في إسكيشهير، وتشتهر بتشغيل واحد من أكبر أنظمة التعليم عن بُعد في العالم إلى جانب برامج قوية في الحرم الجامعي في إدارة الأعمال والإعلام والفنون الجميلة.',
    descriptionTr: "Anadolu Üniversitesi, kökleri 1958'e dayanan Eskişehir'deki bir üniversite olup, işletme, iletişim ve güzel sanatlarda güçlü örgün programların yanı sıra dünyanın en büyük açıköğretim sistemlerinden birini yürütmesiyle tanınmaktadır.",
  },
  {
    slug: 'suleyman-demirel-university',
    nameEn: 'Süleyman Demirel University', nameAr: 'جامعة سليمان ديميرل', nameTr: 'Süleyman Demirel Üniversitesi',
    city: 'isparta', cityEn: 'Isparta', cityAr: 'إسبارطة', cityTr: 'Isparta',
    type: UniversityType.PUBLIC, establishedYear: 1992,
    descriptionEn: 'Süleyman Demirel University was established in 1992 in Isparta and has grown into a comprehensive state university known for its medical school and agricultural sciences programs.',
    descriptionAr: 'تأسست جامعة سليمان ديميرل عام 1992 في إسبارطة، وتطورت لتصبح جامعة حكومية شاملة تشتهر بكلية الطب وبرامج العلوم الزراعية.',
    descriptionTr: 'Süleyman Demirel Üniversitesi, 1992 yılında Isparta\'da kurulmuş olup tıp fakültesi ve ziraat bilimleri programlarıyla tanınan kapsamlı bir devlet üniversitesi haline gelmiştir.',
  },
  {
    slug: 'ondokuz-mayis-university',
    nameEn: 'Ondokuz Mayıs University', nameAr: 'جامعة أون دوكوز مايس', nameTr: 'Ondokuz Mayıs Üniversitesi',
    city: 'samsun', cityEn: 'Samsun', cityAr: 'سامسون', cityTr: 'Samsun',
    type: UniversityType.PUBLIC, establishedYear: 1975,
    descriptionEn: 'Ondokuz Mayıs University was founded in 1975 in the Black Sea city of Samsun and offers a wide range of programs across medicine, engineering, agriculture and the humanities.',
    descriptionAr: 'تأسست جامعة أون دوكوز مايس عام 1975 في مدينة سامسون على البحر الأسود، وتقدم مجموعة واسعة من البرامج في الطب والهندسة والزراعة والعلوم الإنسانية.',
    descriptionTr: 'Ondokuz Mayıs Üniversitesi, 1975 yılında Karadeniz kıyısındaki Samsun\'da kurulmuş olup tıp, mühendislik, ziraat ve beşeri bilimler alanlarında geniş bir program yelpazesi sunmaktadır.',
  },
  {
    slug: 'dicle-university',
    nameEn: 'Dicle University', nameAr: 'جامعة دجلة', nameTr: 'Dicle Üniversitesi',
    city: 'diyarbakir', cityEn: 'Diyarbakır', cityAr: 'ديار بكر', cityTr: 'Diyarbakır',
    type: UniversityType.PUBLIC, establishedYear: 1974,
    descriptionEn: 'Dicle University was established in 1974 in Diyarbakır and serves as a major state university for southeastern Turkey, with a comprehensive medical school and engineering faculties.',
    descriptionAr: 'تأسست جامعة دجلة عام 1974 في ديار بكر، وتُعدّ جامعة حكومية رئيسية لجنوب شرق تركيا، بكلية طب شاملة وكليات هندسية.',
    descriptionTr: 'Dicle Üniversitesi, 1974 yılında Diyarbakır\'da kurulmuş olup kapsamlı bir tıp fakültesi ve mühendislik fakülteleriyle Güneydoğu Anadolu\'nun başlıca devlet üniversitesi olarak hizmet vermektedir.',
  },
  {
    slug: 'firat-university',
    nameEn: 'Fırat University', nameAr: 'جامعة فرات', nameTr: 'Fırat Üniversitesi',
    city: 'elazig', cityEn: 'Elazığ', cityAr: 'إلازيغ', cityTr: 'Elazığ',
    type: UniversityType.PUBLIC, establishedYear: 1975,
    descriptionEn: "Fırat University was founded in 1975 in Elazığ and is one of eastern Turkey's leading state universities, with well-regarded medicine, veterinary medicine and engineering faculties.",
    descriptionAr: 'تأسست جامعة فرات عام 1975 في إلازيغ، وهي واحدة من أبرز الجامعات الحكومية في شرق تركيا، بكليات طب وطب بيطري وهندسة معروفة.',
    descriptionTr: "Fırat Üniversitesi, 1975 yılında Elazığ'da kurulmuş olup, saygın tıp, veteriner hekimliği ve mühendislik fakülteleriyle Doğu Anadolu'nun önde gelen devlet üniversitelerinden biridir.",
  },
  {
    slug: 'gaziantep-university',
    nameEn: 'Gaziantep University', nameAr: 'جامعة غازي عنتاب', nameTr: 'Gaziantep Üniversitesi',
    city: 'gaziantep', cityEn: 'Gaziantep', cityAr: 'غازي عنتاب', cityTr: 'Gaziantep',
    type: UniversityType.PUBLIC, establishedYear: 1987,
    descriptionEn: 'Gaziantep University gained independent university status in 1987 in the southeastern city of Gaziantep, offering strong engineering, medicine and business programs.',
    descriptionAr: 'حصلت جامعة غازي عنتاب على مكانة جامعة مستقلة عام 1987 في مدينة غازي عنتاب جنوب شرق تركيا، وتقدم برامج قوية في الهندسة والطب وإدارة الأعمال.',
    descriptionTr: 'Gaziantep Üniversitesi, 1987 yılında Güneydoğu Anadolu\'daki Gaziantep şehrinde bağımsız üniversite statüsü kazanmış olup güçlü mühendislik, tıp ve işletme programları sunmaktadır.',
  },
  {
    slug: 'kocaeli-university',
    nameEn: 'Kocaeli University', nameAr: 'جامعة كوجالي', nameTr: 'Kocaeli Üniversitesi',
    city: 'kocaeli', cityEn: 'Kocaeli', cityAr: 'كوجالي', cityTr: 'Kocaeli',
    type: UniversityType.PUBLIC, establishedYear: 1992,
    descriptionEn: 'Kocaeli University was established in 1992 in the industrial city of İzmit (Kocaeli), offering strong engineering and technology programs close to Istanbul.',
    descriptionAr: 'تأسست جامعة كوجالي عام 1992 في مدينة إزميت (كوجالي) الصناعية، وتقدم برامج قوية في الهندسة والتكنولوجيا بالقرب من إسطنبول.',
    descriptionTr: 'Kocaeli Üniversitesi, 1992 yılında sanayi şehri İzmit\'te (Kocaeli) kurulmuş olup İstanbul\'a yakın konumda güçlü mühendislik ve teknoloji programları sunmaktadır.',
  },
  {
    slug: 'sakarya-university',
    nameEn: 'Sakarya University', nameAr: 'جامعة سكاريا', nameTr: 'Sakarya Üniversitesi',
    city: 'sakarya', cityEn: 'Sakarya', cityAr: 'سكاريا', cityTr: 'Sakarya',
    type: UniversityType.PUBLIC, establishedYear: 1992,
    descriptionEn: 'Sakarya University gained full university status in 1992, building on an engineering academy dating to the 1970s, and is known today for its engineering, computer science and business programs.',
    descriptionAr: 'حصلت جامعة سكاريا على مكانة جامعة كاملة عام 1992، استناداً إلى أكاديمية هندسية يعود تاريخها إلى السبعينيات، وتشتهر اليوم ببرامجها في الهندسة وعلوم الحاسوب وإدارة الأعمال.',
    descriptionTr: 'Sakarya Üniversitesi, 1970\'lere dayanan bir mühendislik akademisinin temelleri üzerine 1992\'de tam üniversite statüsü kazanmış olup bugün mühendislik, bilgisayar bilimleri ve işletme programlarıyla tanınmaktadır.',
  },
  {
    slug: 'pamukkale-university',
    nameEn: 'Pamukkale University', nameAr: 'جامعة باموكالة', nameTr: 'Pamukkale Üniversitesi',
    city: 'denizli', cityEn: 'Denizli', cityAr: 'دنيزلي', cityTr: 'Denizli',
    type: UniversityType.PUBLIC, establishedYear: 1992,
    descriptionEn: 'Pamukkale University was founded in 1992 in Denizli, near the famous Pamukkale travertines, and offers a broad range of programs in medicine, engineering and education.',
    descriptionAr: 'تأسست جامعة باموكالة عام 1992 في دنيزلي، بالقرب من مصاطب باموكالة الشهيرة، وتقدم مجموعة واسعة من البرامج في الطب والهندسة والتربية.',
    descriptionTr: 'Pamukkale Üniversitesi, 1992 yılında ünlü Pamukkale travertenlerine yakın Denizli\'de kurulmuş olup tıp, mühendislik ve eğitim alanlarında geniş bir program yelpazesi sunmaktadır.',
  },
  {
    slug: 'mersin-university',
    nameEn: 'Mersin University', nameAr: 'جامعة مرسين', nameTr: 'Mersin Üniversitesi',
    city: 'mersin', cityEn: 'Mersin', cityAr: 'مرسين', cityTr: 'Mersin',
    type: UniversityType.PUBLIC, establishedYear: 1992,
    descriptionEn: 'Mersin University was established in 1992 in the Mediterranean port city of Mersin, offering programs across engineering, business, fisheries and tourism.',
    descriptionAr: 'تأسست جامعة مرسين عام 1992 في مدينة مرسين الساحلية المتوسطية، وتقدم برامج في الهندسة وإدارة الأعمال ومصايد الأسماك والسياحة.',
    descriptionTr: 'Mersin Üniversitesi, 1992 yılında Akdeniz\'deki liman şehri Mersin\'de kurulmuş olup mühendislik, işletme, su ürünleri ve turizm alanlarında programlar sunmaktadır.',
  },
  {
    slug: 'eskisehir-osmangazi-university',
    nameEn: 'Eskişehir Osmangazi University', nameAr: 'جامعة إسكيشهير عثمان غازي', nameTr: 'Eskişehir Osmangazi Üniversitesi',
    city: 'eskisehir', cityEn: 'Eskişehir', cityAr: 'إسكيشهير', cityTr: 'Eskişehir',
    type: UniversityType.PUBLIC, establishedYear: 1993,
    descriptionEn: 'Eskişehir Osmangazi University was founded in 1993, separating from Anadolu University, and today runs strong medical, engineering and agricultural programs in Eskişehir.',
    descriptionAr: 'تأسست جامعة إسكيشهير عثمان غازي عام 1993 بعد انفصالها عن جامعة الأناضول، وتدير اليوم برامج قوية في الطب والهندسة والزراعة في إسكيشهير.',
    descriptionTr: 'Eskişehir Osmangazi Üniversitesi, 1993 yılında Anadolu Üniversitesi\'nden ayrılarak kurulmuş olup bugün Eskişehir\'de güçlü tıp, mühendislik ve ziraat programları yürütmektedir.',
  },
  {
    slug: 'necmettin-erbakan-university',
    nameEn: 'Necmettin Erbakan University', nameAr: 'جامعة نجم الدين أربكان', nameTr: 'Necmettin Erbakan Üniversitesi',
    city: 'konya', cityEn: 'Konya', cityAr: 'قونيا', cityTr: 'Konya',
    type: UniversityType.PUBLIC, establishedYear: 2010,
    descriptionEn: 'Necmettin Erbakan University was established in 2010 in Konya, formed from faculties separated from Selçuk University, with a focus on medicine, education and Islamic sciences.',
    descriptionAr: 'تأسست جامعة نجم الدين أربكان عام 2010 في قونيا، وتشكلت من كليات انفصلت عن جامعة سلجوق، مع تركيز على الطب والتربية والعلوم الإسلامية.',
    descriptionTr: 'Necmettin Erbakan Üniversitesi, 2010 yılında Konya\'da Selçuk Üniversitesi\'nden ayrılan fakültelerden oluşarak kurulmuş olup tıp, eğitim ve İslami ilimlere odaklanmaktadır.',
  },
  {
    slug: 'van-yuzuncu-yil-university',
    nameEn: 'Van Yüzüncü Yıl University', nameAr: 'جامعة وان يوزنجو يل', nameTr: 'Van Yüzüncü Yıl Üniversitesi',
    city: 'van', cityEn: 'Van', cityAr: 'وان', cityTr: 'Van',
    type: UniversityType.PUBLIC, establishedYear: 1982,
    descriptionEn: 'Van Yüzüncü Yıl University was established in 1982 in the eastern city of Van, on the shores of Lake Van, offering programs in medicine, veterinary science, agriculture and engineering.',
    descriptionAr: 'تأسست جامعة وان يوزنجو يل عام 1982 في مدينة وان الشرقية، على ضفاف بحيرة وان، وتقدم برامج في الطب والطب البيطري والزراعة والهندسة.',
    descriptionTr: 'Van Yüzüncü Yıl Üniversitesi, 1982 yılında Van Gölü kıyısındaki Van şehrinde kurulmuş olup tıp, veteriner hekimliği, ziraat ve mühendislik alanlarında programlar sunmaktadır.',
  },
  {
    slug: 'sivas-cumhuriyet-university',
    nameEn: 'Sivas Cumhuriyet University', nameAr: 'جامعة سيواس جمهوريت', nameTr: 'Sivas Cumhuriyet Üniversitesi',
    city: 'sivas', cityEn: 'Sivas', cityAr: 'سيواس', cityTr: 'Sivas',
    type: UniversityType.PUBLIC, establishedYear: 1974,
    descriptionEn: 'Sivas Cumhuriyet University was founded in 1974 in the central Anatolian city of Sivas, with well-regarded medical and engineering faculties.',
    descriptionAr: 'تأسست جامعة سيواس جمهوريت عام 1974 في مدينة سيواس بوسط الأناضول، بكليات طب وهندسة معروفة.',
    descriptionTr: 'Sivas Cumhuriyet Üniversitesi, 1974 yılında Orta Anadolu\'daki Sivas şehrinde kurulmuş olup saygın tıp ve mühendislik fakültelerine sahiptir.',
  },
  {
    slug: 'trakya-university',
    nameEn: 'Trakya University', nameAr: 'جامعة تراقيا', nameTr: 'Trakya Üniversitesi',
    city: 'edirne', cityEn: 'Edirne', cityAr: 'أدرنة', cityTr: 'Edirne',
    type: UniversityType.PUBLIC, establishedYear: 1982,
    descriptionEn: "Trakya University was established in 1982 in the historic city of Edirne near Turkey's borders with Greece and Bulgaria, offering programs in medicine, engineering, agriculture and fine arts.",
    descriptionAr: 'تأسست جامعة تراقيا عام 1982 في مدينة أدرنة التاريخية بالقرب من حدود تركيا مع اليونان وبلغاريا، وتقدم برامج في الطب والهندسة والزراعة والفنون الجميلة.',
    descriptionTr: "Trakya Üniversitesi, 1982 yılında Türkiye'nin Yunanistan ve Bulgaristan sınırlarına yakın tarihi Edirne şehrinde kurulmuş olup tıp, mühendislik, ziraat ve güzel sanatlar alanlarında programlar sunmaktadır.",
  },
  {
    slug: 'mugla-sitki-kocman-university',
    nameEn: 'Muğla Sıtkı Koçman University', nameAr: 'جامعة موغلا سيتكي كوتشمان', nameTr: 'Muğla Sıtkı Koçman Üniversitesi',
    city: 'mugla', cityEn: 'Muğla', cityAr: 'موغلا', cityTr: 'Muğla',
    type: UniversityType.PUBLIC, establishedYear: 1992,
    descriptionEn: 'Muğla Sıtkı Koçman University was founded in 1992 in the coastal province of Muğla, offering programs in tourism, marine sciences, engineering and education.',
    descriptionAr: 'تأسست جامعة موغلا سيتكي كوتشمان عام 1992 في محافظة موغلا الساحلية، وتقدم برامج في السياحة والعلوم البحرية والهندسة والتربية.',
    descriptionTr: 'Muğla Sıtkı Koçman Üniversitesi, 1992 yılında sahil ili Muğla\'da kurulmuş olup turizm, deniz bilimleri, mühendislik ve eğitim alanlarında programlar sunmaktadır.',
  },
  {
    slug: 'manisa-celal-bayar-university',
    nameEn: 'Manisa Celal Bayar University', nameAr: 'جامعة مانيسا جلال بايار', nameTr: 'Manisa Celal Bayar Üniversitesi',
    city: 'manisa', cityEn: 'Manisa', cityAr: 'مانيسا', cityTr: 'Manisa',
    type: UniversityType.PUBLIC, establishedYear: 1992,
    descriptionEn: 'Manisa Celal Bayar University was established in 1992 in the Aegean city of Manisa, offering a range of programs in medicine, engineering and agriculture.',
    descriptionAr: 'تأسست جامعة مانيسا جلال بايار عام 1992 في مدينة مانيسا الإيجية، وتقدم مجموعة من البرامج في الطب والهندسة والزراعة.',
    descriptionTr: 'Manisa Celal Bayar Üniversitesi, 1992 yılında Ege bölgesindeki Manisa şehrinde kurulmuş olup tıp, mühendislik ve ziraat alanlarında çeşitli programlar sunmaktadır.',
  },
  {
    slug: 'kahramanmaras-sutcu-imam-university',
    nameEn: 'Kahramanmaraş Sütçü İmam University', nameAr: 'جامعة قهرمان مرعش سوتشو إمام', nameTr: 'Kahramanmaraş Sütçü İmam Üniversitesi',
    city: 'kahramanmaras', cityEn: 'Kahramanmaraş', cityAr: 'قهرمان مرعش', cityTr: 'Kahramanmaraş',
    type: UniversityType.PUBLIC, establishedYear: 1992,
    descriptionEn: 'Kahramanmaraş Sütçü İmam University was founded in 1992 in Kahramanmaraş, southeastern Turkey, with strong agriculture, engineering and forestry programs.',
    descriptionAr: 'تأسست جامعة قهرمان مرعش سوتشو إمام عام 1992 في قهرمان مرعش بجنوب شرق تركيا، ببرامج قوية في الزراعة والهندسة والغابات.',
    descriptionTr: 'Kahramanmaraş Sütçü İmam Üniversitesi, 1992 yılında Güneydoğu Anadolu\'daki Kahramanmaraş\'ta kurulmuş olup güçlü ziraat, mühendislik ve orman fakültelerine sahiptir.',
  },
  {
    slug: 'afyon-kocatepe-university',
    nameEn: 'Afyon Kocatepe University', nameAr: 'جامعة أفيون كوجاتبه', nameTr: 'Afyon Kocatepe Üniversitesi',
    city: 'afyonkarahisar', cityEn: 'Afyonkarahisar', cityAr: 'أفيون قره حصار', cityTr: 'Afyonkarahisar',
    type: UniversityType.PUBLIC, establishedYear: 1992,
    descriptionEn: 'Afyon Kocatepe University was established in 1992 in Afyonkarahisar, offering a broad range of programs including medicine, veterinary science and engineering.',
    descriptionAr: 'تأسست جامعة أفيون كوجاتبه عام 1992 في أفيون قره حصار، وتقدم مجموعة واسعة من البرامج بما في ذلك الطب والطب البيطري والهندسة.',
    descriptionTr: 'Afyon Kocatepe Üniversitesi, 1992 yılında Afyonkarahisar\'da kurulmuş olup tıp, veteriner hekimliği ve mühendislik dahil geniş bir program yelpazesi sunmaktadır.',
  },
  {
    slug: 'balikesir-university',
    nameEn: 'Balıkesir University', nameAr: 'جامعة باليكسير', nameTr: 'Balıkesir Üniversitesi',
    city: 'balikesir', cityEn: 'Balıkesir', cityAr: 'باليكسير', cityTr: 'Balıkesir',
    type: UniversityType.PUBLIC, establishedYear: 1992,
    descriptionEn: 'Balıkesir University was founded in 1992 in the western city of Balıkesir, offering programs across engineering, medicine, tourism and marine sciences.',
    descriptionAr: 'تأسست جامعة باليكسير عام 1992 في مدينة باليكسير الغربية، وتقدم برامج في الهندسة والطب والسياحة والعلوم البحرية.',
    descriptionTr: 'Balıkesir Üniversitesi, 1992 yılında Batı Anadolu\'daki Balıkesir şehrinde kurulmuş olup mühendislik, tıp, turizm ve deniz bilimleri alanlarında programlar sunmaktadır.',
  },
]

async function main() {
  console.log(`Seeding ${universities.length} Turkish state universities (upsert, non-destructive)...`)
  let created = 0
  let updated = 0
  for (const uni of universities) {
    const existing = await prisma.university.findUnique({ where: { slug: uni.slug } })
    await prisma.university.upsert({
      where: { slug: uni.slug },
      update: uni,
      create: { ...uni, isActive: true, isFeatured: false },
    })
    if (existing) updated++
    else created++
  }
  console.log(`Done. Created ${created}, updated ${updated}.`)
}

main()
  .catch((e) => { console.error(e); process.exit(1) })
  .finally(async () => { await prisma.$disconnect() })
